#ifndef LVGL_FRAMES_H
#define LVGL_FRAMES_H

// Auto-generated by generate_frames_header.py

#ifdef __has_include
#if __has_include("lvgl.h")
#ifndef LV_LVGL_H_INCLUDE_SIMPLE
#define LV_LVGL_H_INCLUDE_SIMPLE
#endif
#endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#include <stdint.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#define FRAME_WIDTH 320
#define FRAME_HEIGHT 240

#define FRAME_DSC(index) \
  { \
      .header = { \
          .magic = LV_IMAGE_HEADER_MAGIC, \
          .cf = LV_COLOR_FORMAT_RGB565A8, \
          .flags = 0 | LV_IMAGE_FLAGS_COMPRESSED, \
          .w = FRAME_WIDTH, \
          .h = FRAME_HEIGHT, \
          .stride = FRAME_WIDTH * 2, \
          .reserved_2 = 1, \
      }, \
      .data_size = (size_t)(_binary_frame_##index##_bin_end - _binary_frame_##index##_bin_start), \
      .data = _binary_frame_##index##_bin_start + 12, \
      .reserved = 0, \
  }

// Extern binary symbols
extern const uint8_t _binary_frame_000_bin_start[];
extern const uint8_t _binary_frame_000_bin_end[];
extern const uint8_t _binary_frame_001_bin_start[];
extern const uint8_t _binary_frame_001_bin_end[];
extern const uint8_t _binary_frame_002_bin_start[];
extern const uint8_t _binary_frame_002_bin_end[];
extern const uint8_t _binary_frame_003_bin_start[];
extern const uint8_t _binary_frame_003_bin_end[];
extern const uint8_t _binary_frame_004_bin_start[];
extern const uint8_t _binary_frame_004_bin_end[];
extern const uint8_t _binary_frame_005_bin_start[];
extern const uint8_t _binary_frame_005_bin_end[];
extern const uint8_t _binary_frame_006_bin_start[];
extern const uint8_t _binary_frame_006_bin_end[];
extern const uint8_t _binary_frame_007_bin_start[];
extern const uint8_t _binary_frame_007_bin_end[];
extern const uint8_t _binary_frame_008_bin_start[];
extern const uint8_t _binary_frame_008_bin_end[];
extern const uint8_t _binary_frame_009_bin_start[];
extern const uint8_t _binary_frame_009_bin_end[];
extern const uint8_t _binary_frame_010_bin_start[];
extern const uint8_t _binary_frame_010_bin_end[];
extern const uint8_t _binary_frame_011_bin_start[];
extern const uint8_t _binary_frame_011_bin_end[];
extern const uint8_t _binary_frame_012_bin_start[];
extern const uint8_t _binary_frame_012_bin_end[];
extern const uint8_t _binary_frame_013_bin_start[];
extern const uint8_t _binary_frame_013_bin_end[];
extern const uint8_t _binary_frame_014_bin_start[];
extern const uint8_t _binary_frame_014_bin_end[];
extern const uint8_t _binary_frame_015_bin_start[];
extern const uint8_t _binary_frame_015_bin_end[];
extern const uint8_t _binary_frame_016_bin_start[];
extern const uint8_t _binary_frame_016_bin_end[];
extern const uint8_t _binary_frame_017_bin_start[];
extern const uint8_t _binary_frame_017_bin_end[];
extern const uint8_t _binary_frame_018_bin_start[];
extern const uint8_t _binary_frame_018_bin_end[];
extern const uint8_t _binary_frame_019_bin_start[];
extern const uint8_t _binary_frame_019_bin_end[];
extern const uint8_t _binary_frame_020_bin_start[];
extern const uint8_t _binary_frame_020_bin_end[];
extern const uint8_t _binary_frame_021_bin_start[];
extern const uint8_t _binary_frame_021_bin_end[];
extern const uint8_t _binary_frame_022_bin_start[];
extern const uint8_t _binary_frame_022_bin_end[];
extern const uint8_t _binary_frame_023_bin_start[];
extern const uint8_t _binary_frame_023_bin_end[];
extern const uint8_t _binary_frame_024_bin_start[];
extern const uint8_t _binary_frame_024_bin_end[];
extern const uint8_t _binary_frame_025_bin_start[];
extern const uint8_t _binary_frame_025_bin_end[];
extern const uint8_t _binary_frame_026_bin_start[];
extern const uint8_t _binary_frame_026_bin_end[];
extern const uint8_t _binary_frame_027_bin_start[];
extern const uint8_t _binary_frame_027_bin_end[];
extern const uint8_t _binary_frame_028_bin_start[];
extern const uint8_t _binary_frame_028_bin_end[];
extern const uint8_t _binary_frame_029_bin_start[];
extern const uint8_t _binary_frame_029_bin_end[];
extern const uint8_t _binary_frame_030_bin_start[];
extern const uint8_t _binary_frame_030_bin_end[];
extern const uint8_t _binary_frame_031_bin_start[];
extern const uint8_t _binary_frame_031_bin_end[];
extern const uint8_t _binary_frame_032_bin_start[];
extern const uint8_t _binary_frame_032_bin_end[];
extern const uint8_t _binary_frame_033_bin_start[];
extern const uint8_t _binary_frame_033_bin_end[];
extern const uint8_t _binary_frame_034_bin_start[];
extern const uint8_t _binary_frame_034_bin_end[];
extern const uint8_t _binary_frame_035_bin_start[];
extern const uint8_t _binary_frame_035_bin_end[];
extern const uint8_t _binary_frame_036_bin_start[];
extern const uint8_t _binary_frame_036_bin_end[];
extern const uint8_t _binary_frame_037_bin_start[];
extern const uint8_t _binary_frame_037_bin_end[];
extern const uint8_t _binary_frame_038_bin_start[];
extern const uint8_t _binary_frame_038_bin_end[];
extern const uint8_t _binary_frame_039_bin_start[];
extern const uint8_t _binary_frame_039_bin_end[];
extern const uint8_t _binary_frame_040_bin_start[];
extern const uint8_t _binary_frame_040_bin_end[];
extern const uint8_t _binary_frame_041_bin_start[];
extern const uint8_t _binary_frame_041_bin_end[];
extern const uint8_t _binary_frame_042_bin_start[];
extern const uint8_t _binary_frame_042_bin_end[];
extern const uint8_t _binary_frame_043_bin_start[];
extern const uint8_t _binary_frame_043_bin_end[];
extern const uint8_t _binary_frame_044_bin_start[];
extern const uint8_t _binary_frame_044_bin_end[];
extern const uint8_t _binary_frame_045_bin_start[];
extern const uint8_t _binary_frame_045_bin_end[];
extern const uint8_t _binary_frame_046_bin_start[];
extern const uint8_t _binary_frame_046_bin_end[];
extern const uint8_t _binary_frame_047_bin_start[];
extern const uint8_t _binary_frame_047_bin_end[];
extern const uint8_t _binary_frame_048_bin_start[];
extern const uint8_t _binary_frame_048_bin_end[];
extern const uint8_t _binary_frame_049_bin_start[];
extern const uint8_t _binary_frame_049_bin_end[];
extern const uint8_t _binary_frame_050_bin_start[];
extern const uint8_t _binary_frame_050_bin_end[];
extern const uint8_t _binary_frame_051_bin_start[];
extern const uint8_t _binary_frame_051_bin_end[];
extern const uint8_t _binary_frame_052_bin_start[];
extern const uint8_t _binary_frame_052_bin_end[];
extern const uint8_t _binary_frame_053_bin_start[];
extern const uint8_t _binary_frame_053_bin_end[];
extern const uint8_t _binary_frame_054_bin_start[];
extern const uint8_t _binary_frame_054_bin_end[];
extern const uint8_t _binary_frame_055_bin_start[];
extern const uint8_t _binary_frame_055_bin_end[];
extern const uint8_t _binary_frame_056_bin_start[];
extern const uint8_t _binary_frame_056_bin_end[];
extern const uint8_t _binary_frame_057_bin_start[];
extern const uint8_t _binary_frame_057_bin_end[];
extern const uint8_t _binary_frame_058_bin_start[];
extern const uint8_t _binary_frame_058_bin_end[];
extern const uint8_t _binary_frame_059_bin_start[];
extern const uint8_t _binary_frame_059_bin_end[];
extern const uint8_t _binary_frame_060_bin_start[];
extern const uint8_t _binary_frame_060_bin_end[];
extern const uint8_t _binary_frame_061_bin_start[];
extern const uint8_t _binary_frame_061_bin_end[];
extern const uint8_t _binary_frame_062_bin_start[];
extern const uint8_t _binary_frame_062_bin_end[];
extern const uint8_t _binary_frame_063_bin_start[];
extern const uint8_t _binary_frame_063_bin_end[];
extern const uint8_t _binary_frame_064_bin_start[];
extern const uint8_t _binary_frame_064_bin_end[];
extern const uint8_t _binary_frame_065_bin_start[];
extern const uint8_t _binary_frame_065_bin_end[];
extern const uint8_t _binary_frame_066_bin_start[];
extern const uint8_t _binary_frame_066_bin_end[];
extern const uint8_t _binary_frame_067_bin_start[];
extern const uint8_t _binary_frame_067_bin_end[];
extern const uint8_t _binary_frame_068_bin_start[];
extern const uint8_t _binary_frame_068_bin_end[];
extern const uint8_t _binary_frame_069_bin_start[];
extern const uint8_t _binary_frame_069_bin_end[];
extern const uint8_t _binary_frame_070_bin_start[];
extern const uint8_t _binary_frame_070_bin_end[];
extern const uint8_t _binary_frame_071_bin_start[];
extern const uint8_t _binary_frame_071_bin_end[];
extern const uint8_t _binary_frame_072_bin_start[];
extern const uint8_t _binary_frame_072_bin_end[];
extern const uint8_t _binary_frame_073_bin_start[];
extern const uint8_t _binary_frame_073_bin_end[];
extern const uint8_t _binary_frame_074_bin_start[];
extern const uint8_t _binary_frame_074_bin_end[];
extern const uint8_t _binary_frame_075_bin_start[];
extern const uint8_t _binary_frame_075_bin_end[];
extern const uint8_t _binary_frame_076_bin_start[];
extern const uint8_t _binary_frame_076_bin_end[];
extern const uint8_t _binary_frame_077_bin_start[];
extern const uint8_t _binary_frame_077_bin_end[];
extern const uint8_t _binary_frame_078_bin_start[];
extern const uint8_t _binary_frame_078_bin_end[];
extern const uint8_t _binary_frame_079_bin_start[];
extern const uint8_t _binary_frame_079_bin_end[];
extern const uint8_t _binary_frame_080_bin_start[];
extern const uint8_t _binary_frame_080_bin_end[];
extern const uint8_t _binary_frame_081_bin_start[];
extern const uint8_t _binary_frame_081_bin_end[];
extern const uint8_t _binary_frame_082_bin_start[];
extern const uint8_t _binary_frame_082_bin_end[];
extern const uint8_t _binary_frame_083_bin_start[];
extern const uint8_t _binary_frame_083_bin_end[];
extern const uint8_t _binary_frame_084_bin_start[];
extern const uint8_t _binary_frame_084_bin_end[];
extern const uint8_t _binary_frame_085_bin_start[];
extern const uint8_t _binary_frame_085_bin_end[];
extern const uint8_t _binary_frame_086_bin_start[];
extern const uint8_t _binary_frame_086_bin_end[];
extern const uint8_t _binary_frame_087_bin_start[];
extern const uint8_t _binary_frame_087_bin_end[];
extern const uint8_t _binary_frame_088_bin_start[];
extern const uint8_t _binary_frame_088_bin_end[];
extern const uint8_t _binary_frame_089_bin_start[];
extern const uint8_t _binary_frame_089_bin_end[];
extern const uint8_t _binary_frame_090_bin_start[];
extern const uint8_t _binary_frame_090_bin_end[];
extern const uint8_t _binary_frame_091_bin_start[];
extern const uint8_t _binary_frame_091_bin_end[];
extern const uint8_t _binary_frame_092_bin_start[];
extern const uint8_t _binary_frame_092_bin_end[];
extern const uint8_t _binary_frame_093_bin_start[];
extern const uint8_t _binary_frame_093_bin_end[];
extern const uint8_t _binary_frame_094_bin_start[];
extern const uint8_t _binary_frame_094_bin_end[];
extern const uint8_t _binary_frame_095_bin_start[];
extern const uint8_t _binary_frame_095_bin_end[];
extern const uint8_t _binary_frame_096_bin_start[];
extern const uint8_t _binary_frame_096_bin_end[];
extern const uint8_t _binary_frame_097_bin_start[];
extern const uint8_t _binary_frame_097_bin_end[];
extern const uint8_t _binary_frame_098_bin_start[];
extern const uint8_t _binary_frame_098_bin_end[];
extern const uint8_t _binary_frame_099_bin_start[];
extern const uint8_t _binary_frame_099_bin_end[];
extern const uint8_t _binary_frame_100_bin_start[];
extern const uint8_t _binary_frame_100_bin_end[];
extern const uint8_t _binary_frame_101_bin_start[];
extern const uint8_t _binary_frame_101_bin_end[];
extern const uint8_t _binary_frame_102_bin_start[];
extern const uint8_t _binary_frame_102_bin_end[];
extern const uint8_t _binary_frame_103_bin_start[];
extern const uint8_t _binary_frame_103_bin_end[];
extern const uint8_t _binary_frame_104_bin_start[];
extern const uint8_t _binary_frame_104_bin_end[];
extern const uint8_t _binary_frame_105_bin_start[];
extern const uint8_t _binary_frame_105_bin_end[];
extern const uint8_t _binary_frame_106_bin_start[];
extern const uint8_t _binary_frame_106_bin_end[];
extern const uint8_t _binary_frame_107_bin_start[];
extern const uint8_t _binary_frame_107_bin_end[];
extern const uint8_t _binary_frame_108_bin_start[];
extern const uint8_t _binary_frame_108_bin_end[];
extern const uint8_t _binary_frame_109_bin_start[];
extern const uint8_t _binary_frame_109_bin_end[];
extern const uint8_t _binary_frame_110_bin_start[];
extern const uint8_t _binary_frame_110_bin_end[];
extern const uint8_t _binary_frame_111_bin_start[];
extern const uint8_t _binary_frame_111_bin_end[];
extern const uint8_t _binary_frame_112_bin_start[];
extern const uint8_t _binary_frame_112_bin_end[];
extern const uint8_t _binary_frame_113_bin_start[];
extern const uint8_t _binary_frame_113_bin_end[];
extern const uint8_t _binary_frame_114_bin_start[];
extern const uint8_t _binary_frame_114_bin_end[];
extern const uint8_t _binary_frame_115_bin_start[];
extern const uint8_t _binary_frame_115_bin_end[];
extern const uint8_t _binary_frame_116_bin_start[];
extern const uint8_t _binary_frame_116_bin_end[];
extern const uint8_t _binary_frame_117_bin_start[];
extern const uint8_t _binary_frame_117_bin_end[];
extern const uint8_t _binary_frame_118_bin_start[];
extern const uint8_t _binary_frame_118_bin_end[];

static const lv_image_dsc_t frames[] = {
    FRAME_DSC(000),
    FRAME_DSC(001),
    FRAME_DSC(002),
    FRAME_DSC(003),
    FRAME_DSC(004),
    FRAME_DSC(005),
    FRAME_DSC(006),
    FRAME_DSC(007),
    FRAME_DSC(008),
    FRAME_DSC(009),
    FRAME_DSC(010),
    FRAME_DSC(011),
    FRAME_DSC(012),
    FRAME_DSC(013),
    FRAME_DSC(014),
    FRAME_DSC(015),
    FRAME_DSC(016),
    FRAME_DSC(017),
    FRAME_DSC(018),
    FRAME_DSC(019),
    FRAME_DSC(020),
    FRAME_DSC(021),
    FRAME_DSC(022),
    FRAME_DSC(023),
    FRAME_DSC(024),
    FRAME_DSC(025),
    FRAME_DSC(026),
    FRAME_DSC(027),
    FRAME_DSC(028),
    FRAME_DSC(029),
    FRAME_DSC(030),
    FRAME_DSC(031),
    FRAME_DSC(032),
    FRAME_DSC(033),
    FRAME_DSC(034),
    FRAME_DSC(035),
    FRAME_DSC(036),
    FRAME_DSC(037),
    FRAME_DSC(038),
    FRAME_DSC(039),
    FRAME_DSC(040),
    FRAME_DSC(041),
    FRAME_DSC(042),
    FRAME_DSC(043),
    FRAME_DSC(044),
    FRAME_DSC(045),
    FRAME_DSC(046),
    FRAME_DSC(047),
    FRAME_DSC(048),
    FRAME_DSC(049),
    FRAME_DSC(050),
    FRAME_DSC(051),
    FRAME_DSC(052),
    FRAME_DSC(053),
    FRAME_DSC(054),
    FRAME_DSC(055),
    FRAME_DSC(056),
    FRAME_DSC(057),
    FRAME_DSC(058),
    FRAME_DSC(059),
    FRAME_DSC(060),
    FRAME_DSC(061),
    FRAME_DSC(062),
    FRAME_DSC(063),
    FRAME_DSC(064),
    FRAME_DSC(065),
    FRAME_DSC(066),
    FRAME_DSC(067),
    FRAME_DSC(068),
    FRAME_DSC(069),
    FRAME_DSC(070),
    FRAME_DSC(071),
    FRAME_DSC(072),
    FRAME_DSC(073),
    FRAME_DSC(074),
    FRAME_DSC(075),
    FRAME_DSC(076),
    FRAME_DSC(077),
    FRAME_DSC(078),
    FRAME_DSC(079),
    FRAME_DSC(080),
    FRAME_DSC(081),
    FRAME_DSC(082),
    FRAME_DSC(083),
    FRAME_DSC(084),
    FRAME_DSC(085),
    FRAME_DSC(086),
    FRAME_DSC(087),
    FRAME_DSC(088),
    FRAME_DSC(089),
    FRAME_DSC(090),
    FRAME_DSC(091),
    FRAME_DSC(092),
    FRAME_DSC(093),
    FRAME_DSC(094),
    FRAME_DSC(095),
    FRAME_DSC(096),
    FRAME_DSC(097),
    FRAME_DSC(098),
    FRAME_DSC(099),
    FRAME_DSC(100),
    FRAME_DSC(101),
    FRAME_DSC(102),
    FRAME_DSC(103),
    FRAME_DSC(104),
    FRAME_DSC(105),
    FRAME_DSC(106),
    FRAME_DSC(107),
    FRAME_DSC(108),
    FRAME_DSC(109),
    FRAME_DSC(110),
    FRAME_DSC(111),
    FRAME_DSC(112),
    FRAME_DSC(113),
    FRAME_DSC(114),
    FRAME_DSC(115),
    FRAME_DSC(116),
    FRAME_DSC(117),
    FRAME_DSC(118),
};

static const int frames_count = sizeof(frames) / sizeof(lv_image_dsc_t);

#endif // LVGL_FRAMES_H
