#ifndef LVGL_FRAMES_H
#define LVGL_FRAMES_H

// Auto-generated by generate_frames_header.py

#ifdef __has_include
#if __has_include("lvgl.h")
#ifndef LV_LVGL_H_INCLUDE_SIMPLE
#define LV_LVGL_H_INCLUDE_SIMPLE
#endif
#endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#include <stdint.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#define FRAME_WIDTH 320
#define FRAME_HEIGHT 240

#define FRAME_DSC(index) \
  { \
      .header = { \
          .magic = LV_IMAGE_HEADER_MAGIC, \
          .cf = LV_COLOR_FORMAT_RGB565A8, \
          .flags = 0 | LV_IMAGE_FLAGS_COMPRESSED, \
          .w = FRAME_WIDTH, \
          .h = FRAME_HEIGHT, \
          .stride = FRAME_WIDTH * 2, \
          .reserved_2 = 1, \
      }, \
      .data_size = (size_t)(_binary_frame_##index##_bin_end - _binary_frame_##index##_bin_start), \
      .data = _binary_frame_##index##_bin_start + 12, \
      .reserved = 0, \
  }

// Extern binary symbols
extern const uint8_t _binary_frame_00_bin_start[];
extern const uint8_t _binary_frame_00_bin_end[];
extern const uint8_t _binary_frame_01_bin_start[];
extern const uint8_t _binary_frame_01_bin_end[];
extern const uint8_t _binary_frame_02_bin_start[];
extern const uint8_t _binary_frame_02_bin_end[];
extern const uint8_t _binary_frame_03_bin_start[];
extern const uint8_t _binary_frame_03_bin_end[];
extern const uint8_t _binary_frame_04_bin_start[];
extern const uint8_t _binary_frame_04_bin_end[];
extern const uint8_t _binary_frame_05_bin_start[];
extern const uint8_t _binary_frame_05_bin_end[];
extern const uint8_t _binary_frame_06_bin_start[];
extern const uint8_t _binary_frame_06_bin_end[];
extern const uint8_t _binary_frame_07_bin_start[];
extern const uint8_t _binary_frame_07_bin_end[];
extern const uint8_t _binary_frame_08_bin_start[];
extern const uint8_t _binary_frame_08_bin_end[];
extern const uint8_t _binary_frame_09_bin_start[];
extern const uint8_t _binary_frame_09_bin_end[];
extern const uint8_t _binary_frame_10_bin_start[];
extern const uint8_t _binary_frame_10_bin_end[];
extern const uint8_t _binary_frame_11_bin_start[];
extern const uint8_t _binary_frame_11_bin_end[];
extern const uint8_t _binary_frame_12_bin_start[];
extern const uint8_t _binary_frame_12_bin_end[];
extern const uint8_t _binary_frame_13_bin_start[];
extern const uint8_t _binary_frame_13_bin_end[];
extern const uint8_t _binary_frame_14_bin_start[];
extern const uint8_t _binary_frame_14_bin_end[];
extern const uint8_t _binary_frame_15_bin_start[];
extern const uint8_t _binary_frame_15_bin_end[];
extern const uint8_t _binary_frame_16_bin_start[];
extern const uint8_t _binary_frame_16_bin_end[];
extern const uint8_t _binary_frame_17_bin_start[];
extern const uint8_t _binary_frame_17_bin_end[];
extern const uint8_t _binary_frame_18_bin_start[];
extern const uint8_t _binary_frame_18_bin_end[];
extern const uint8_t _binary_frame_19_bin_start[];
extern const uint8_t _binary_frame_19_bin_end[];
extern const uint8_t _binary_frame_20_bin_start[];
extern const uint8_t _binary_frame_20_bin_end[];
extern const uint8_t _binary_frame_21_bin_start[];
extern const uint8_t _binary_frame_21_bin_end[];
extern const uint8_t _binary_frame_22_bin_start[];
extern const uint8_t _binary_frame_22_bin_end[];
extern const uint8_t _binary_frame_23_bin_start[];
extern const uint8_t _binary_frame_23_bin_end[];
extern const uint8_t _binary_frame_24_bin_start[];
extern const uint8_t _binary_frame_24_bin_end[];
extern const uint8_t _binary_frame_25_bin_start[];
extern const uint8_t _binary_frame_25_bin_end[];
extern const uint8_t _binary_frame_26_bin_start[];
extern const uint8_t _binary_frame_26_bin_end[];
extern const uint8_t _binary_frame_27_bin_start[];
extern const uint8_t _binary_frame_27_bin_end[];
extern const uint8_t _binary_frame_28_bin_start[];
extern const uint8_t _binary_frame_28_bin_end[];
extern const uint8_t _binary_frame_29_bin_start[];
extern const uint8_t _binary_frame_29_bin_end[];
extern const uint8_t _binary_frame_30_bin_start[];
extern const uint8_t _binary_frame_30_bin_end[];
extern const uint8_t _binary_frame_31_bin_start[];
extern const uint8_t _binary_frame_31_bin_end[];
extern const uint8_t _binary_frame_32_bin_start[];
extern const uint8_t _binary_frame_32_bin_end[];
extern const uint8_t _binary_frame_33_bin_start[];
extern const uint8_t _binary_frame_33_bin_end[];
extern const uint8_t _binary_frame_34_bin_start[];
extern const uint8_t _binary_frame_34_bin_end[];
extern const uint8_t _binary_frame_35_bin_start[];
extern const uint8_t _binary_frame_35_bin_end[];
extern const uint8_t _binary_frame_36_bin_start[];
extern const uint8_t _binary_frame_36_bin_end[];
extern const uint8_t _binary_frame_37_bin_start[];
extern const uint8_t _binary_frame_37_bin_end[];
extern const uint8_t _binary_frame_38_bin_start[];
extern const uint8_t _binary_frame_38_bin_end[];
extern const uint8_t _binary_frame_39_bin_start[];
extern const uint8_t _binary_frame_39_bin_end[];
extern const uint8_t _binary_frame_40_bin_start[];
extern const uint8_t _binary_frame_40_bin_end[];
extern const uint8_t _binary_frame_41_bin_start[];
extern const uint8_t _binary_frame_41_bin_end[];
extern const uint8_t _binary_frame_42_bin_start[];
extern const uint8_t _binary_frame_42_bin_end[];
extern const uint8_t _binary_frame_43_bin_start[];
extern const uint8_t _binary_frame_43_bin_end[];
extern const uint8_t _binary_frame_44_bin_start[];
extern const uint8_t _binary_frame_44_bin_end[];
extern const uint8_t _binary_frame_45_bin_start[];
extern const uint8_t _binary_frame_45_bin_end[];
extern const uint8_t _binary_frame_46_bin_start[];
extern const uint8_t _binary_frame_46_bin_end[];
extern const uint8_t _binary_frame_47_bin_start[];
extern const uint8_t _binary_frame_47_bin_end[];
extern const uint8_t _binary_frame_48_bin_start[];
extern const uint8_t _binary_frame_48_bin_end[];
extern const uint8_t _binary_frame_49_bin_start[];
extern const uint8_t _binary_frame_49_bin_end[];
extern const uint8_t _binary_frame_50_bin_start[];
extern const uint8_t _binary_frame_50_bin_end[];
extern const uint8_t _binary_frame_51_bin_start[];
extern const uint8_t _binary_frame_51_bin_end[];
extern const uint8_t _binary_frame_52_bin_start[];
extern const uint8_t _binary_frame_52_bin_end[];
extern const uint8_t _binary_frame_53_bin_start[];
extern const uint8_t _binary_frame_53_bin_end[];
extern const uint8_t _binary_frame_54_bin_start[];
extern const uint8_t _binary_frame_54_bin_end[];
extern const uint8_t _binary_frame_55_bin_start[];
extern const uint8_t _binary_frame_55_bin_end[];
extern const uint8_t _binary_frame_56_bin_start[];
extern const uint8_t _binary_frame_56_bin_end[];
extern const uint8_t _binary_frame_57_bin_start[];
extern const uint8_t _binary_frame_57_bin_end[];
extern const uint8_t _binary_frame_58_bin_start[];
extern const uint8_t _binary_frame_58_bin_end[];
extern const uint8_t _binary_frame_59_bin_start[];
extern const uint8_t _binary_frame_59_bin_end[];
extern const uint8_t _binary_frame_60_bin_start[];
extern const uint8_t _binary_frame_60_bin_end[];
extern const uint8_t _binary_frame_61_bin_start[];
extern const uint8_t _binary_frame_61_bin_end[];
extern const uint8_t _binary_frame_62_bin_start[];
extern const uint8_t _binary_frame_62_bin_end[];
extern const uint8_t _binary_frame_63_bin_start[];
extern const uint8_t _binary_frame_63_bin_end[];
extern const uint8_t _binary_frame_64_bin_start[];
extern const uint8_t _binary_frame_64_bin_end[];
extern const uint8_t _binary_frame_65_bin_start[];
extern const uint8_t _binary_frame_65_bin_end[];
extern const uint8_t _binary_frame_66_bin_start[];
extern const uint8_t _binary_frame_66_bin_end[];
extern const uint8_t _binary_frame_67_bin_start[];
extern const uint8_t _binary_frame_67_bin_end[];
extern const uint8_t _binary_frame_68_bin_start[];
extern const uint8_t _binary_frame_68_bin_end[];
extern const uint8_t _binary_frame_69_bin_start[];
extern const uint8_t _binary_frame_69_bin_end[];
extern const uint8_t _binary_frame_70_bin_start[];
extern const uint8_t _binary_frame_70_bin_end[];
extern const uint8_t _binary_frame_71_bin_start[];
extern const uint8_t _binary_frame_71_bin_end[];
extern const uint8_t _binary_frame_72_bin_start[];
extern const uint8_t _binary_frame_72_bin_end[];
extern const uint8_t _binary_frame_73_bin_start[];
extern const uint8_t _binary_frame_73_bin_end[];
extern const uint8_t _binary_frame_74_bin_start[];
extern const uint8_t _binary_frame_74_bin_end[];
extern const uint8_t _binary_frame_75_bin_start[];
extern const uint8_t _binary_frame_75_bin_end[];
extern const uint8_t _binary_frame_76_bin_start[];
extern const uint8_t _binary_frame_76_bin_end[];
extern const uint8_t _binary_frame_77_bin_start[];
extern const uint8_t _binary_frame_77_bin_end[];
extern const uint8_t _binary_frame_78_bin_start[];
extern const uint8_t _binary_frame_78_bin_end[];
extern const uint8_t _binary_frame_79_bin_start[];
extern const uint8_t _binary_frame_79_bin_end[];
extern const uint8_t _binary_frame_80_bin_start[];
extern const uint8_t _binary_frame_80_bin_end[];
extern const uint8_t _binary_frame_81_bin_start[];
extern const uint8_t _binary_frame_81_bin_end[];
extern const uint8_t _binary_frame_82_bin_start[];
extern const uint8_t _binary_frame_82_bin_end[];
extern const uint8_t _binary_frame_83_bin_start[];
extern const uint8_t _binary_frame_83_bin_end[];
extern const uint8_t _binary_frame_84_bin_start[];
extern const uint8_t _binary_frame_84_bin_end[];
extern const uint8_t _binary_frame_85_bin_start[];
extern const uint8_t _binary_frame_85_bin_end[];
extern const uint8_t _binary_frame_86_bin_start[];
extern const uint8_t _binary_frame_86_bin_end[];
extern const uint8_t _binary_frame_87_bin_start[];
extern const uint8_t _binary_frame_87_bin_end[];
extern const uint8_t _binary_frame_88_bin_start[];
extern const uint8_t _binary_frame_88_bin_end[];
extern const uint8_t _binary_frame_89_bin_start[];
extern const uint8_t _binary_frame_89_bin_end[];
extern const uint8_t _binary_frame_90_bin_start[];
extern const uint8_t _binary_frame_90_bin_end[];
extern const uint8_t _binary_frame_91_bin_start[];
extern const uint8_t _binary_frame_91_bin_end[];
extern const uint8_t _binary_frame_92_bin_start[];
extern const uint8_t _binary_frame_92_bin_end[];
extern const uint8_t _binary_frame_93_bin_start[];
extern const uint8_t _binary_frame_93_bin_end[];
extern const uint8_t _binary_frame_94_bin_start[];
extern const uint8_t _binary_frame_94_bin_end[];
extern const uint8_t _binary_frame_95_bin_start[];
extern const uint8_t _binary_frame_95_bin_end[];

static const lv_image_dsc_t frames[] = {
    FRAME_DSC(00),
    FRAME_DSC(01),
    FRAME_DSC(02),
    FRAME_DSC(03),
    FRAME_DSC(04),
    FRAME_DSC(05),
    FRAME_DSC(06),
    FRAME_DSC(07),
    FRAME_DSC(08),
    FRAME_DSC(09),
    FRAME_DSC(10),
    FRAME_DSC(11),
    FRAME_DSC(12),
    FRAME_DSC(13),
    FRAME_DSC(14),
    FRAME_DSC(15),
    FRAME_DSC(16),
    FRAME_DSC(17),
    FRAME_DSC(18),
    FRAME_DSC(19),
    FRAME_DSC(20),
    FRAME_DSC(21),
    FRAME_DSC(22),
    FRAME_DSC(23),
    FRAME_DSC(24),
    FRAME_DSC(25),
    FRAME_DSC(26),
    FRAME_DSC(27),
    FRAME_DSC(28),
    FRAME_DSC(29),
    FRAME_DSC(30),
    FRAME_DSC(31),
    FRAME_DSC(32),
    FRAME_DSC(33),
    FRAME_DSC(34),
    FRAME_DSC(35),
    FRAME_DSC(36),
    FRAME_DSC(37),
    FRAME_DSC(38),
    FRAME_DSC(39),
    FRAME_DSC(40),
    FRAME_DSC(41),
    FRAME_DSC(42),
    FRAME_DSC(43),
    FRAME_DSC(44),
    FRAME_DSC(45),
    FRAME_DSC(46),
    FRAME_DSC(47),
    FRAME_DSC(48),
    FRAME_DSC(49),
    FRAME_DSC(50),
    FRAME_DSC(51),
    FRAME_DSC(52),
    FRAME_DSC(53),
    FRAME_DSC(54),
    FRAME_DSC(55),
    FRAME_DSC(56),
    FRAME_DSC(57),
    FRAME_DSC(58),
    FRAME_DSC(59),
    FRAME_DSC(60),
    FRAME_DSC(61),
    FRAME_DSC(62),
    FRAME_DSC(63),
    FRAME_DSC(64),
    FRAME_DSC(65),
    FRAME_DSC(66),
    FRAME_DSC(67),
    FRAME_DSC(68),
    FRAME_DSC(69),
    FRAME_DSC(70),
    FRAME_DSC(71),
    FRAME_DSC(72),
    FRAME_DSC(73),
    FRAME_DSC(74),
    FRAME_DSC(75),
    FRAME_DSC(76),
    FRAME_DSC(77),
    FRAME_DSC(78),
    FRAME_DSC(79),
    FRAME_DSC(80),
    FRAME_DSC(81),
    FRAME_DSC(82),
    FRAME_DSC(83),
    FRAME_DSC(84),
    FRAME_DSC(85),
    FRAME_DSC(86),
    FRAME_DSC(87),
    FRAME_DSC(88),
    FRAME_DSC(89),
    FRAME_DSC(90),
    FRAME_DSC(91),
    FRAME_DSC(92),
    FRAME_DSC(93),
    FRAME_DSC(94),
    FRAME_DSC(95),
};

static const int frames_count = sizeof(frames) / sizeof(lv_image_dsc_t);

#endif // LVGL_FRAMES_H
