#ifndef CONFIG_H

// BOARD
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define TOUCH_BUTTON_GPIO GPIO_NUM_10

// LED
#define LED_GPIO GPIO_NUM_48
#define LED_PWM_GPIO GPIO_NUM_18

// SDCARD
// #define SDCARD_ENABLE true
#define SD_NUM_MISO GPIO_NUM_0
#define SD_NUM_MOSI GPIO_NUM_1
#define SD_NUM_CLK GPIO_NUM_2
#define SD_NUM_CS GPIO_NUM_3

// I2S
#define AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#ifdef AUDIO_I2S_METHOD_SIMPLEX
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_20
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_21
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_10

#define AUDIO_I2S_MIC_GPIO_DIN GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_WS GPIO_NUM_6
#define AUDIO_I2S_MIC_GPIO_SCK GPIO_NUM_7
#else
#define AUDIO_I2S_GPIO_WS GPIO_NUM_4
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_21
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_10
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7
#endif

// OLED
#define OLED_I2C_ADDRESS 0X3C
#define OLED_I2C_SCL GPIO_NUM_21
#define OLED_I2C_SDA GPIO_NUM_20
#define OLED_WIDTH 128
#define OLED_HEIGHT 64

// DISPLAY
#define OLED_DISPLAY false
#define LCD_DISPLAY true
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY true
#define DISPLAY_INVERT_COLOR true
#define DISPLAY_OFFSET_X 20
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_BG_PEROID 40000
#define DISPLAY_UPDATE_PEROID 1000000 * 100


// LCD
#define LCD_SPI_MODE 0
#define LCD_WIDTH 280
#define LCD_HEIGHT 240
#define LCD_BG_COLOR 0xFFFFFF
#define LCD_CLOCK_COLOR 0xFFFFFF
#define LCD_CLOCK_VERTICAL false

#define LCD_TYPE_ST7789_SERIAL
// #define LCD_TYPE_ST7735_SERIAL
// #define LCD_TYPE_ILI9341_SERIAL
// #define LCD_TYPE_GC9A01_SERIAL

#ifdef LCD_TYPE_GC9A01_SERIAL
#endif

#ifdef LCD_TYPE_ILI9341_SERIAL
#define LCD_RGB_ORDER LCD_RGB_ELEMENT_ORDER_BGR
#define LCD_BLK_PIN GPIO_NUM_5
#define LCD_SCL_PIN GPIO_NUM_6
#define LCD_SDA_PIN GPIO_NUM_4
#define LCD_RST_PIN GPIO_NUM_3

#define LCD_DC_PIN GPIO_NUM_1
#define LCD_CS_PIN GPIO_NUM_2
#endif

#ifdef LCD_TYPE_ST7735_SERIAL
#define LCD_RGB_ORDER LCD_RGB_ELEMENT_ORDER_RGB
#define LCD_BLK_PIN GPIO_NUM_7
#define LCD_SCL_PIN GPIO_NUM_4
#define LCD_SDA_PIN GPIO_NUM_3
#define LCD_RST_PIN GPIO_NUM_2

#define LCD_DC_PIN GPIO_NUM_1
#define LCD_CS_PIN GPIO_NUM_0
#endif

#ifdef LCD_TYPE_ST7789_SERIAL
#define LCD_RGB_ORDER LCD_RGB_ELEMENT_ORDER_RGB
#define LCD_BLK_PIN GPIO_NUM_5
#define LCD_SCL_PIN GPIO_NUM_6
#define LCD_SDA_PIN GPIO_NUM_4
#define LCD_RST_PIN GPIO_NUM_3

#define LCD_DC_PIN GPIO_NUM_1
#define LCD_CS_PIN GPIO_NUM_2
#endif

// UART
#define UART_TX GPIO_NUM_15
#define UART_RX GPIO_NUM_16

#endif // CONFIG_H