#ifndef CONFIG_H

// BOARD
#define BOOT_BUTTON_GPIO GPIO_NUM_9
#define TOUCH_BUTTON_GPIO GPIO_NUM_10

// LED
#define LED_GPIO GPIO_NUM_8
#define LED_PWM_GPIO GPIO_NUM_0

// OLED
#define OLED_I2C_ADDRESS 0X3C
#define OLED_I2C_SCL GPIO_NUM_21
#define OLED_I2C_SDA GPIO_NUM_20

// LCD
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_42
#define LCD_SCL_PIN GPIO_NUM_18
#define LCD_SDA_PIN GPIO_NUM_19
#define LCD_RST_PIN GPIO_NUM_12

#define LCD_DC_PIN GPIO_NUM_4
#define LCD_CS_PIN GPIO_NUM_5

#define LCD_SPI_MODE 0
#define LCD_RGB_ORDER LCD_RGB_ELEMENT_ORDER_RGB

// UART
#define UART_TX GPIO_NUM_6
#define UART_RX GPIO_NUM_7

// DISPLAY
#define OLED_DISPLAY true
#define LCD_DISPLAY false
#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 64
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR true
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#endif // CONFIG_H