import os
import subprocess

current_dir = os.path.dirname(os.path.abspath(__file__))

# 运行 rename.py
subprocess.run(["python", f"{current_dir}/rename.py"], check=True)

# ==== 配置 ====

current_dir = os.path.dirname(os.path.abspath(__file__))
bin_directory = "../main/files/frames"
full_path = os.path.join(current_dir, bin_directory)
bin_full_path = os.path.normpath(full_path)

header_directory = "../main/assets/frames.h"
full_path = os.path.join(current_dir, header_directory)
header_full_path = os.path.normpath(full_path)

bin_dir = bin_full_path
output_h = header_full_path
macro = "LVGL_FRAMES_H"  # 头文件保护宏名
frame_prefix = "frame"   # 可修改为其他前缀
frame_width = 200
frame_height = 210

# ==== 收集文件 ====
bin_files = sorted(f for f in os.listdir(bin_dir) if f.endswith(".bin"))
frame_names = [os.path.splitext(f)[0] for f in bin_files]  # frame_00
frame_indices = [name.split("_")[-1] for name in frame_names]

# ==== 写入头文件 ====
with open(output_h, "w") as f:
    # 头部宏保护、LVGL 兼容包含
    header = f"""\
#ifndef {macro}
#define {macro}

// Auto-generated by generate_frames_header.py

#ifdef __has_include
#if __has_include("lvgl.h")
#ifndef LV_LVGL_H_INCLUDE_SIMPLE
#define LV_LVGL_H_INCLUDE_SIMPLE
#endif
#endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#include <stdint.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#define FRAME_WIDTH {frame_width}
#define FRAME_HEIGHT {frame_height}

#define FRAME_DSC(index) \\
  {{ \\
      .header = {{ \\
          .magic = LV_IMAGE_HEADER_MAGIC, \\
          .cf = LV_COLOR_FORMAT_RGB565, \\
          .flags = 0 | LV_IMAGE_FLAGS_COMPRESSED, \\
          .w = FRAME_WIDTH, \\
          .h = FRAME_HEIGHT, \\
          .stride = FRAME_WIDTH * 2, \\
          .reserved_2 = 1, \\
      }}, \\
      .data_size = (size_t)(_binary_{frame_prefix}_##index##_bin_end - _binary_{frame_prefix}_##index##_bin_start), \\
      .data = _binary_{frame_prefix}_##index##_bin_start + 12, \\
      .reserved = 0, \\
  }}

"""
    f.write(header)

    # extern 声明
    f.write("// Extern binary symbols\n")
    for name in frame_names:
        f.write(f"extern const uint8_t _binary_{name}_bin_start[];\n")
        f.write(f"extern const uint8_t _binary_{name}_bin_end[];\n")
    f.write("\n")

    # frames[] 定义
    f.write("static const lv_image_dsc_t frames[] = {\n")
    for index in frame_indices:
        f.write(f"    FRAME_DSC({index}),\n")
    f.write("};\n\n")

    f.write("static const int frames_count = sizeof(frames) / sizeof(lv_image_dsc_t);\n")
    f.write(f"\n#endif // {macro}\n")

print(f"✅ Header file generated: {output_h}")
